# Tasca 2A: Estructura d'una Matriu

Roger Gallart

20 abril 2021

## Nivell 1
Treballem els conceptes de l'estructura d'una matriu, dimensió, eixos i la vectorització que ens permet reduir l'ús de for loops en operacions aritmètiques o matemàtiques.

### Exercici 1
Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.

In [73]:
import numpy as np
from random import randint

x = np.array([randint(0,10) for _ in range(8)], dtype='i8') #i8 = integer of 8 bytes = 64 bits = int64

print(f'L\'array x és: {x}')
print(f'Les dimensions de x són: {x.shape}')



L'array x és: [ 9 10  6  9  4  5  4  2]
Les dimensions de x són: (8,)


### Exercici 2
De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

In [75]:
m = np.mean(x)
print(f'El valor mitjà dels elements de x és: {m}')

x2 = x - m
print(f'Si restem la mitjana dels valors de x, obtenim: {x2}')

El valor mitjà dels elements de x és: 6.125
Si restem la mitjana dels valors de x, obtenim: [ 2.875  3.875 -0.125  2.875 -2.125 -1.125 -2.125 -4.125]


### Exercici 3
Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos

In [77]:
# Creem una llista de 25 enters aleatoris, el convertim en un ndarray 1D de 
# 25 elements, i finalment el reformatem a una matriu de 5x5
y = np.array([randint(0,10) for _ in range(25)], dtype='i8').reshape(5,5)

print(f'La matriu bidimensional y és:\n {y}')
print(f'El valor màxim de la matriu y és: {np.max(y)}')
print(f'Els valors màxims de cada columna de y són: {np.max(y,axis=0)}')
print(f'Els valors màxims de cada fila de y són: {np.max(y, axis=1)}')

La matriu bidimensional y és:
 [[ 2  5  5 10  0]
 [ 1  4  0  9  4]
 [ 9  9  2  6  4]
 [ 0  2  1  0  5]
 [ 4  8 10 10  4]]
El valor màxim de la matriu y és: 10
Els valors màxims de cada columna de y són: [ 9  9 10 10  5]
Els valors màxims de cada fila de y són: [10  9  9  5 10]


## Nivell 2
Treballem els conceptes de l'estructura d'una matriu, Broadcasting, indexació, Mask.

### Exercici 4

Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".

In [78]:
# Dimensions coincidents
a = np.array([1,2,3,4])[:,np.newaxis]
b = np.array([10,20,30,40])

print(a, f'\nDimensions de a: {a.shape}\n')
print(b, f'\nDimensions de b: {b.shape}\n')

c = a + b
print(c, f'\nDimensions de a+b: {c.shape}\n')

[[1]
 [2]
 [3]
 [4]] 
Dimensions de a: (4, 1)

[10 20 30 40] 
Dimensions de b: (4,)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]
 [14 24 34 44]] 
Dimensions de a+b: (4, 4)



In [80]:
# U
a = np.array([[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]])
b = np.array([1,2,3,4])

print(a, f'\nDimensions de a: {a.shape}\n')
print(b, f'\nDimensions de b: {b.shape}\n')

c = a + b
print(c, f'\nDimensions de a+b: {c.shape}\n')

[[   1    2    3]
 [  10   20   30]
 [ 100  200  300]
 [1000 2000 3000]] 
Dimensions de a: (4, 3)

[1 2 3 4] 
Dimensions de b: (4,)



ValueError: ignored

### Exercici 5
Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.


In [ ]:
print(f'La matriu y és:\n{y}')

col = y[:,2]
print(f'\nLa tercera columna de la matriu y és: {col}\n i la suma del valors dels seus elements és: {col.sum()}')

row = y[3,:]
print(f'\nLa quarta columna de la matriu y és: {row}\n i la suma del valors dels seus elements és: {row.sum()}')

La matriu y és:
[[ 6  6  0  3  7]
 [ 4  8  5  3  1]
 [ 2  9  1  9  7]
 [ 1  6  4  2 10]
 [ 3  8  0 10  0]]

La tercera columna de la matriu y és: [0 5 1 4 0]
 i la suma del valors dels seus elements és: 10

La quarta columna de la matriu y és: [ 1  6  4  2 10]
 i la suma del valors dels seus elements és: 23


### Exercici 6
Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.

In [ ]:
print(f'La matriu y és:\n{y}')

mask = (y % 4 == 0)
print(f'\nQuins elements de la matriu y són divisibles per 4:\n {mask}')

La matriu y és:
[[ 6  6  0  3  7]
 [ 4  8  5  3  1]
 [ 2  9  1  9  7]
 [ 1  6  4  2 10]
 [ 3  8  0 10  0]]

Quins elements de la matriu y són divisibles per 4:
 [[False False  True False False]
 [ True  True False False False]
 [False False False False False]
 [False False  True False False]
 [False  True  True False  True]]


### Exercici 7
A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.

In [ ]:
print(f'Els valors de la matriu y que són divisibles per 4 són: {y[mask]}')

Els valors de la matriu y que són divisibles per 4 són: [0 4 8 4 8 0 0]


## Nivell 3
Manipulació d’imatges amb Matplotlib.

Carregareu qualsevol imatge (jpg, png ..) amb Matplotlib. adoneu-vos que les imatges RGB (Red, Green, Blue) són realment només amplades × alçades × 3 matrius (tres canals Vermell, Verd i Blau), una per cada color de nombres enters int8,

manipuleu aquests bytes i torneu a utilitzar Matplotlib per desar la imatge modificada un cop hàgiu acabat.

Ajuda:Importeu, import matplotlib.image as mpimg. estudieu el metodde mpimg.imread(()

### Exercici 8
Mostreu-me a veure que passa quan eliminem el canal G Verd o B Blau.

Mostreu-me a veure què passa quan eliminem el canal G Verd o B Blau. Hauries d'utilitzar la indexació per seleccionar el canal que voleu anul·lar.

Utilitzar el mètode, mpimg.imsave () de la llibreria importada, per guardar les imatges modificades i que haureu de pujar al vostre repositori a github.

In [68]:
import matplotlib.image as mpimg

url = 'https://i.pinimg.com/originals/c1/f3/95/c1f395d9d3634e0773e64abbdafc90ac.png'
img_RGB = mpimg.imread(url)

print(f'Les dimensions de la imatge importada: {img_RGB.shape}')

Les dimensions de la imatge importada: (290, 500, 3)


In [70]:
# Si eliminem el canal G Verd
img_RB = img_RGB.copy()
img_RB[:,:,1] = 0
mpimg.imsave('img_senseVerd.png', img_RB)

In [72]:
# Si eliminem el canal B Blau
img_RG = img_RGB.copy()
img_RG[:,:,2] = 0
mpimg.imsave('img_senseBlau.png', img_RG)